/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Copy: typeof import('./src/components/Copy.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    DataBase: typeof import('./src/components/DataBase.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FileView: typeof import('./src/components/view/FileView.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageView: typeof import('./src/components/view/ImageView.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Shortcut: typeof import('./src/components/Shortcut.vue')['default']
    TextView: typeof import('./src/components/view/TextView.vue')['default']
    View: typeof import('./src/components/view/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
