/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoTooltip: typeof import('./src/components/AutoTooltip.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    ColorBlock: typeof import('./src/components/ColorBlock.vue')['default']
    ColorView: typeof import('./src/components/view/ColorView.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileView: typeof import('./src/components/view/FileView.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HotkeyTooltip: typeof import('./src/components/HotkeyTooltip.vue')['default']
    ImageView: typeof import('./src/components/view/ImageView.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    SettingPanel: typeof import('./src/components/SettingPanel.vue')['default']
    Shortcut: typeof import('./src/components/Shortcut.vue')['default']
    TextView: typeof import('./src/components/view/TextView.vue')['default']
    TypeIcon: typeof import('./src/components/TypeIcon.vue')['default']
    View: typeof import('./src/components/view/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
