name: test

on:
  push:
    branches:
      - main # 你想触发这个工作流的分支，可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v2
        with:
          # 根据需要设置 Node.js 版本
          # node-version: lts/*
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Run test script
        run: yarn test
